services:
  - type: web
    name: claims-risk-api
    runtime: docker
    dockerfilePath: ./Dockerfile
    dockerContext: .
    healthCheckPath: /health
    plan: free

  - type: web
    name: claims-risk-dashboard
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run dashboard.py --server.address=0.0.0.0 --server.port=$PORT
    envVars:
      - key: API_URL
        value: https://claims-risk-api-zspx.onrender.com
    plan: free
